import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css"
const Contact = (props) => {
    return <div className={styles.container}>
        <Head>
        <title>Contact person</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <h1>Contact</h1>
        </div>
        
    </div>
  }
  
  export default Contact